In [1]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import StandardScaler

In [2]:
df = fetch_california_housing(as_frame=True)
type(df)

sklearn.utils._bunch.Bunch

In [3]:
x = df.data
y = df.target

In [4]:
#df = pd.DataFrame(df.data, columns = df.feature_names)
#df['Price'] = df.target

In [5]:
x.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [6]:
x.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   

            Latitude  Longitude  
MedInc     -0.079809  -0.015176  
HouseAge    0.011173  -0.108197  
AveRooms    0.106389  -0.027540  
AveBedrms   0.069721   0.013344  
Population -0.108785   0.099773  
AveOccup    0.002366   0.002476  
Latitude    1.000000  -0.924664  
Longitude  -0.924664   1.000000

In [7]:
x = df.data
y = df.target
x
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [8]:
vit_data = pd.DataFrame()
vit_data['Features'] = x.columns
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
vit_data['VIF'] = [variance_inflation_factor(x_scaled,i) for i in range(x_scaled.shape[1])]
vit_data

Features       VIF
0      MedInc  2.501295
1    HouseAge  1.241254
2    AveRooms  8.342786
3   AveBedrms  6.994995
4  Population  1.138125
5    AveOccup  1.008324
6    Latitude  9.297624
7   Longitude  8.962263

In [9]:
x.shape[1]

8

In [10]:
x = x[['MedInc','HouseAge','AveRooms','Population','AveOccup','Latitude']]
x_scaled = scaler.fit_transform(x)
x_scaled

array([[ 2.34476576,  0.98214266,  0.62855945, -0.9744286 , -0.04959654,
         1.05254828],
       [ 2.33223796, -0.60701891,  0.32704136,  0.86143887, -0.09251223,
         1.04318455],
       [ 1.7826994 ,  1.85618152,  1.15562047, -0.82077735, -0.02584253,
         1.03850269],
       ...,
       [-1.14259331, -0.92485123, -0.09031802, -0.3695372 , -0.0717345 ,
         1.77823747],
       [-1.05458292, -0.84539315, -0.04021111, -0.60442933, -0.09122515,
         1.77823747],
       [-0.78012947, -1.00430931, -0.07044252, -0.03397701, -0.04368215,
         1.75014627]])

In [42]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=2)

In [43]:
x_train.shape

(16512, 6)

In [44]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [45]:
model.fit(x_train, y_train)
model.intercept_
model.coef_

array([ 0.84206885,  0.21537355, -0.07889417,  0.0165016 , -0.05136596,
       -0.09351123])

In [46]:
y_pred =model.predict(x_test)
y_pred

array([2.99706676, 1.77216194, 1.29541554, ..., 1.49648217, 1.2911361 ,
       2.3085403 ])

In [47]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [48]:
print('Mearn Absolute Error is ',mean_absolute_error(y_test,y_pred))
print('Mearn Square Error is ',mean_squared_error(y_test,y_pred))
print('R2_Score is ',r2_score(y_test,y_pred))

Mearn Absolute Error is  0.602864612986759
Mearn Square Error is  0.672051914899051
R2_Score is  0.5010840787595766


#LASSO Rregression Algorithem

In [50]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet

In [53]:
#Initialize Model
lasso_model = Lasso()
#Train model
lasso_model.fit(x_train, y_train)
#Predict the model
lasso_y_pred = lasso_model.predict(x_test)
print('lasso - Mearn Absolute Error is ',mean_absolute_error(y_test,lasso_y_pred))
print('lasso - Mearn Square Error is ',mean_squared_error(y_test,lasso_y_pred))
print('lasso - R2_Score is ',r2_score(y_test,lasso_y_pred))

lasso - Mearn Absolute Error is  0.9114963592510591
lasso - Mearn Square Error is  1.3473246598968645
lasso - R2_Score is  -0.0002229128435049521


#Ridge Rregression Algorithem

In [54]:
#Initialize Model
ridge_model = Ridge()
#Train model
ridge_model.fit(x_train, y_train)
#Predict the model
ridge_y_pred = ridge_model.predict(x_test)
print('Ridge - Mearn Absolute Error is ',mean_absolute_error(y_test,ridge_y_pred ))
print('Ridge - Mearn Square Error is ',mean_squared_error(y_test,ridge_y_pred ))
print('Ridge - R2_Score is ',r2_score(y_test,ridge_y_pred ))

Ridge - Mearn Absolute Error is  0.6028674738150163
Ridge - Mearn Square Error is  0.672043984461446
Ridge - R2_Score is  0.501089966134489


#ElasticNet Rregression Algorithem

In [55]:
#Initialize Model
EN = ElasticNet()
#Train model
EN.fit(x_train, y_train)
#Predict the model
EN_y_pred = EN.predict(x_test)
print('ElasticNet - Mearn Absolute Error is ',mean_absolute_error(y_test,EN_y_pred ))
print('ElasticNet - Mearn Square Error is ',mean_squared_error(y_test,EN_y_pred ))
print('ElasticNet - R2_Score is ',r2_score(y_test,EN_y_pred ))

ElasticNet - Mearn Absolute Error is  0.8120124546460386
ElasticNet - Mearn Square Error is  1.0728511380534493
ElasticNet - R2_Score is  0.20353993191705277


In [57]:
#Decision Tree Regressor algorithm
from sklearn.tree import DecisionTreeRegressor

In [58]:
#Initialize Model
DT = DecisionTreeRegressor()
#Train model
DT.fit(x_train, y_train)
#Predict the model
DT_y_pred = DT.predict(x_test)
print('Decision Tree - Mearn Absolute Error is ',mean_absolute_error(y_test,DT_y_pred ))
print('Decision Tree - Mearn Square Error is ',mean_squared_error(y_test,DT_y_pred ))
print('Decision Tree - R2_Score is ',r2_score(y_test,DT_y_pred ))

Decision Tree - Mearn Absolute Error is  0.5543277277131784
Decision Tree - Mearn Square Error is  0.6875521819521802
Decision Tree - R2_Score is  0.4895770361564079


In [61]:
#Random Forest Algorithm
from sklearn.ensemble import RandomForestRegressor

In [62]:
#Initialize Model
RF = RandomForestRegressor()
#Train model
RF.fit(x_train, y_train)
#Predict the model
RF_y_pred = RF.predict(x_test)
print('Random Forest Algorithm  - Mearn Absolute Error is ',mean_absolute_error(y_test,RF_y_pred ))
print('Random Forest Algorithm  - Mearn Square Error is ',mean_squared_error(y_test,RF_y_pred ))
print('Random Forest Algorithm  - R2_Score is ',r2_score(y_test,RF_y_pred ))

Random Forest Algorithm  - Mearn Absolute Error is  0.41750186385658933
Random Forest Algorithm  - Mearn Square Error is  0.3668894616936475
Random Forest Algorithm  - R2_Score is  0.7276296819989202


In [68]:
#Support Vector Machine Algorithem
from sklearn.svm import SVR

In [64]:
#Initialize Model
svr = SVR()
#Train model
svr.fit(x_train, y_train)
#Predict the model
svr_y_pred = svr.predict(x_test)
print('Support Vector Machine  - Mearn Absolute Error is ',mean_absolute_error(y_test,svr_y_pred ))
print('Support Vector Machine  - Mearn Square Error is ',mean_squared_error(y_test,svr_y_pred ))
print('Support Vector Machine  - R2_Score is ',r2_score(y_test,svr_y_pred ))

Support Vector Machine   - Mearn Absolute Error is  0.4600892539032529
Support Vector Machine   - Mearn Square Error is  0.4556688918141462
Support Vector Machine   - R2_Score is  0.661721870141228


In [67]:
#Gradient Boosting Regressor Algorithm
from sklearn.ensemble import GradientBoostingRegressor

In [66]:
#Initialize Model
gbr = GradientBoostingRegressor()
#Train model
gbr.fit(x_train, y_train)
#Predict the model
gbr_y_pred = g.predict(x_test)
print('Gradient Boosting Regressor - Mearn Absolute Error is ',mean_absolute_error(y_test,gbr_y_pred ))
print('Gradient Boosting Regressor  - Mearn Square Error is ',mean_squared_error(y_test,gbr_y_pred ))
print('Gradient Boosting Regressor  - R2_Score is ',r2_score(y_test,gbr_y_pred ))

Gradient Boosting Regressor - Mearn Absolute Error is  0.4454240754363339
Gradient Boosting Regressor  - Mearn Square Error is  0.3892582289384574
Gradient Boosting Regressor  - R2_Score is  0.7110236224527119
